pub mod capture;
pub mod config;
pub mod diff;
pub mod hotkey;
pub mod live;
#[cfg(feature = "ocr")]
pub mod ocr;
pub mod overlay;
pub mod selector;
pub mod translate;
#[cfg(feature = "tray")]
pub mod tray;
